# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moderator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setBaseSize(QtCore.QSize(1366, 768))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1361, 721))
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Moderator = QtWidgets.QWidget()
        self.tab_Moderator.setObjectName("tab_Moderator")
        self.tabWidget.addTab(self.tab_Moderator, "")
        self.tab_Admin = QtWidgets.QWidget()
        self.tab_Admin.setObjectName("tab_Admin")
        self.tabWidget.addTab(self.tab_Admin, "")
        self.tab_Queue = QtWidgets.QWidget()
        self.tab_Queue.setObjectName("tab_Queue")
        self.tableView = QtWidgets.QTableView(self.tab_Queue)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 1341, 581))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab_Queue, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "eHaW Backend"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Moderator), _translate("MainWindow", "Moderator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Admin), _translate("MainWindow", "Event Admin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Queue), _translate("MainWindow", "Message Queue"))
